nim_worker_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: nim.controller.worker:indexAction
        _sylius:
            paginate: $limit
            sortable: $sorting
            filterable: $criteria

nim_worker_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.worker:createAction
        _sylius:
            redirect: nim_worker_update

nim_worker_update:
    pattern: /{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: nim.controller.worker:updateAction
        _sylius:
            redirect: nim_worker_show

nim_worker_show:
    pattern: /{id}
    methods: [GET]
    defaults:
        _controller: nim.controller.worker:showAction

nim_worker_delete:
    pattern: /{id}
    methods: [DELETE]
    defaults:
        _controller: nim.controller.worker:deleteAction
        _sylius:
            redirect: nim_worker_index