nim_dashboard:
    pattern: /
    defaults: { _controller: NIMWebBundle:Dashboard:index }

nim_mision:
    resource: @NIMMissionBundle/Resources/config/routing/mission.yml
    prefix: /mission

nim_agency:
    resource: @NIMWorkerBundle/Resources/config/routing/agency.yml
    prefix: /agency

nim_worker:
    resource: @NIMWorkerBundle/Resources/config/routing/worker.yml
    prefix: /worker