nim_dashboard:
    pattern: /
    defaults: { _controller: NIMWebBundle:Dashboard:index }
    methods: [GET]

nim_locale_index:
    pattern: /locale
    methods: [GET]
    defaults: { _controller: NIMWebBundle:Locale:index }

nim_locale_update:
    pattern: /locale/update
    methods: [POST]
    defaults: { _controller: NIMWebBundle:Locale:update }

nim_mission:
    resource: @NIMMissionBundle/Resources/config/routing/mission.yml
    prefix: /mission

nim_agency:
    resource: @NIMWorkerBundle/Resources/config/routing/agency.yml
    prefix: /agency

nim_worker:
    resource: @NIMWorkerBundle/Resources/config/routing/worker.yml
    prefix: /worker

nim_vaccine:
    resource: @NIMVaccineBundle/Resources/config/routing/vaccine.yml
    prefix: /vaccine
