
# NiM mission configuration
nim_mission:
    driver: doctrine/orm
    classes:
        mission:
            model: NIM\CoreBundle\Model\Mission
    templates:
        mission: NIMWebBundle:Mission

# NiM worker configuration
nim_worker:
    driver: doctrine/orm
    classes:
        worker:
            model: NIM\CoreBundle\Model\Worker
    templates:
        worker: NIMWebBundle:Worker
        agency: NIMWebBundle:Agency

# NiM core configuration
nim_core:
    driver: doctrine/orm

# NiM vaccine configuration
nim_vaccine:
    driver: doctrine/orm
    classes:
        vaccine:
            model: NIM\CoreBundle\Model\Vaccine
    templates:
        vaccine: NIMWebBundle:Vaccine